// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ETPB_BALLOT_Software
{
    using System.Linq;
    using System.Text;
    using System.Collections;
    using System.Collections.Generic;
    using ETPB_BALLOT_Software;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class BallotTemplateAC : BallotTemplateACBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n\r\n<html>\r\n<head>\r\n\r\n\t<style>\r\n\t\r\n\t#borderimg1 { \r\n\t\tborder: 9px black solid;\r\n\r" +
                    "\n\t\tborder-image:  url(");
            
            #line 24 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc2));
            
            #line default
            #line hidden
            this.Write(@") ;
		border-image-repeat:round;
		 border-image-slice: 34;
		  border-image-outset:1px;
		border-image-width:20px;
		
	}
	</style>
	
	
</head>

<body style=""margin: 20px;"">

<table style=""width:100%"">
        <tr>
 			<td>
			   <p style = ""line-height: 20px;font-weight: bold;"">
			   <img src = ");
            
            #line 42 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
			   </p>
			</td>
 		</tr>
 		<tr>
			<td>&nbsp;</td>
	    </tr>
		<tr>
			<td>
	   			<p style=""font-weight: bold;"">e-PBID :</p> 
	   		</td>		
		</tr>
		<tr>
			<td align=""center"">&nbsp;
			</td>
		</tr>
		<tr>
			<td align=""center"">
			</td>
		</tr>
		<tr>
			<td >
	    		<p  style=""font-weight: bold; text-align:center;"">POSTAL BALLOT PAPER</p>
			</td>
		</tr>

</table>

<hr style=""height:5px; background-color: black;""/>

");
            
            #line 72 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

	if(TTfileDict.Candidate.Count < 9)
	 {                                                                          

            
            #line default
            #line hidden
            this.Write("       <table id=\"borderimg1\" style=\" width:100%; margin-top:25px; \" cellspacing=" +
                    "\"0\" cellpadding=\"7\">\r\n");
            
            #line 77 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

		 for(int i = 0; i < TTfileDict.Candidate.Count; i++)
		   {
			 var j = i+1;

            
            #line default
            #line hidden
            this.Write("\t\t\t <tr>\r\n\t\t\r\n\t\t\t                   <td align=\"center\" style=\"border-right:1px bl" +
                    "ack solid; border-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font" +
                    "-size:20px;\">");
            
            #line 85 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-b" +
                    "ottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px;  font" +
                    "-family:");
            
            #line 88 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 88 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 89 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 89 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 90 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 91 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 93 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 98 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 100 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 105 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    " </tr>\r\n\r\n");
            
            #line 112 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

           }
   
		 for(var i = 0; i < (10 - TTfileDict.Candidate.Count); i++)
			{

            
            #line default
            #line hidden
            this.Write("               <tr style=\"height: 98px;\">\r\n\t\t\t\t <td>&nbsp;</td>\r\n\t\t\t\t</tr>\r\n\t   \r" +
                    "\n");
            
            #line 122 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

            }
  

            
            #line default
            #line hidden
            this.Write("\t   \r\n\t   \r\n\t   </table>\r\n\r\n\r\n");
            
            #line 130 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

     }                                                               

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 135 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

	if(TTfileDict.Candidate.Count == 9)
	 {                                                                        

            
            #line default
            #line hidden
            this.Write("       <table id=\"borderimg1\" style=\" width:100%; margin-top:25px;\" cellspacing=\"" +
                    "0\" cellpadding=\"7\">\r\n");
            
            #line 140 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

		 for(int i = 0; i < TTfileDict.Candidate.Count; i++)
		   {
				 var j = i+1;
				 if(i==8)
				 {

            
            #line default
            #line hidden
            this.Write("\t\t\t \r\n\t\t\t\t   <tr>\r\n\t\t\t\t\r\n\t\t\t\t               <td align=\"center\" style=\"border-righ" +
                    "t:1px black solid; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 150 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:5" +
                    "5%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px;  font-family:");
            
            #line 153 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 153 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px;line-height:0.5 ; font-family" +
                    ":");
            
            #line 154 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 154 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 155 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 156 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 158 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%;\" align=\"center\">\r\n\t" +
                    "\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 163 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 165 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%; height:96px;\">&nbsp" +
                    ";</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 170 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\" width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t   </tr>\r\n");
            
            #line 176 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
		             
	   
				 }
				 else
				 {
				 

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t\t           <td align=\"center\" style=\"border-right:1px black" +
                    " solid; border-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-si" +
                    "ze:20px;\">");
            
            #line 186 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-b" +
                    "ottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px; font-" +
                    "family:");
            
            #line 189 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 189 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.1 ; font-famil" +
                    "y:");
            
            #line 190 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 190 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 191 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 192 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 194 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 199 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 201 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 206 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t</tr>\r\n\r\n");
            
            #line 213 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

                 }
           }

            
            #line default
            #line hidden
            this.Write("  \r\n\t   \r\n\t   </table>\r\n\r\n");
            
            #line 220 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

     }                                                                

            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            
            #line 226 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

	if(TTfileDict.Candidate.Count > 9)
	{                                                                      

            
            #line default
            #line hidden
            this.Write("      <table id=\"borderimg1\" style=\" width:100%; margin-top:25px;\" cellspacing=\"0" +
                    "\" cellpadding=\"7\">\r\n");
            
            #line 231 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

		 for(int i = 0; i < 9; i++)
		   {
				 var j = i+1;
				 if(i==8)
				 {

            
            #line default
            #line hidden
            this.Write("\t\t\t \r\n\t\t\t\t   <tr>\r\n\t\t\t\t\r\n\t\t\t\t                <td align=\"center\" style=\"border-rig" +
                    "ht:1px black solid; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 241 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:5" +
                    "5%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px;  font-family:");
            
            #line 244 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 244 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 245 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 245 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 246 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 247 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 249 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%;\" align=\"center\">\r\n\t" +
                    "\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 254 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 256 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%; height:96px;\">&nbsp" +
                    ";</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 261 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\" width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t   </tr>\r\n");
            
            #line 267 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
		             
	   
				 }
				 else
				 {
				 

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\r\n\t\t\t\t\t           <td align=\"center\" style=\"border-right:1px black" +
                    " solid; border-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-si" +
                    "ze:20px;\">");
            
            #line 277 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-b" +
                    "ottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px;  font" +
                    "-family:");
            
            #line 280 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 280 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 281 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 281 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 282 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 283 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 285 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 290 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 292 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 297 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t</tr>\r\n\r\n");
            
            #line 304 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

                 }
		   }

            
            #line default
            #line hidden
            this.Write("      </table>\r\n");
            
            #line 309 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

          int threshold = 9;
		  int nextLotCount = TTfileDict.Candidate.Count - threshold;
		  int previousLotCount = threshold;
		  while(nextLotCount > 0)
			{                                                                   
			  if(nextLotCount > threshold)
			    {                                                                

            
            #line default
            #line hidden
            this.Write("\t\t\t\t   <p style=\"page-break-after:always;\"></p>\r\n\t\t\t\t   <br />\r\n\t\t\t\t   <table sty" +
                    "le=\"width:100%\">\r\n \t\t\t\t\t\t<tr>\r\n \t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t<p style = \"line-height: 20" +
                    "px;font-weight: bold;\">\r\n\t\t\t\t\t\t\t\t<img src = ");
            
            #line 324 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
								</p>
							</td>
 						</tr>
 						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>
	   							<p style=""font-weight: bold;"">e-PBID :</p> 
	   						</td>		
						</tr>
						<tr>
							<td align=""center"">&nbsp;
							</td>
						</tr>
						<tr>
							<td align=""center"">
							</td>
						</tr>
						<tr>
							<td>
	    						<p style=""font-weight: bold;text-align:center;"">POSTAL BALLOT PAPER</p>
							</td>
						</tr>
					</table>

					<hr style=""height:5px; background-color: black;""/>
					<table id=""borderimg1"" style="" width:100% ; margin-top:25px;"" cellspacing=""0"" cellpadding=""12"">
");
            
            #line 353 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

						for(int i = previousLotCount; i < (previousLotCount + threshold); i++)
						   {  
							 var j = i+1;
							 
                             var lastIndex=(previousLotCount + threshold)-1;
                             if(i==lastIndex)
				               {

            
            #line default
            #line hidden
            this.Write("\t\t\t \r\n\t\t\t\t\t\t\t\t   <tr>\r\n\t\t\t\t\t\t\t\t \r\n\t\t\t\t\t\t\t\t   <td align=\"center\" style=\"border-rig" +
                    "ht:1px black solid; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 365 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:5" +
                    "5%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px; font-family:");
            
            #line 368 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 368 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 369 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 369 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 370 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 371 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 373 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%;\" align=\"center\">\r\n\t" +
                    "\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 378 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 380 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%; height:96px;\">&nbsp" +
                    ";</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 385 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\" width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t   </tr>\r\n");
            
            #line 391 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
	   
							   }
							 else
							   {				 

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t   <td align=\"center\" style=\"border-right:1px blac" +
                    "k solid; border-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-s" +
                    "ize:20px;\">");
            
            #line 399 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t   </td>\r\n\t\t\t\t\t\t\t\t   <td style=\"border-right:1px black solid; bo" +
                    "rder-bottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px;" +
                    " font-family:");
            
            #line 402 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 402 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 403 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 403 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 404 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 405 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t   </td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 407 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 412 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 414 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 419 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t\t\t   </tr>\r\n\r\n");
            
            #line 426 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

                               }
						  } 

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t</table>\r\n \r\n");
            
            #line 432 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
				
                    previousLotCount = previousLotCount + 9;
					nextLotCount = nextLotCount - 9;
				}                                                             
				else                                                              
				 {                                                               
				   if(nextLotCount < threshold)
				   {                                                            
				   

            
            #line default
            #line hidden
            this.Write("                    <p style=\"page-break-after:always;\"></p>\r\n\t\t\t\t\t<br />\r\n\t\t\t\t\t<" +
                    "table style=\"width:100%\">\r\n \t\t\t\t\t\t\t<tr>\r\n \t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t   <p style = \"l" +
                    "ine-height: 20px;font-weight: bold;\">\r\n\t\t\t\t\t\t\t\t   <img src = ");
            
            #line 448 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
								   </p>
								</td>
 							</tr>
 							<tr>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>
	   								<p style=""font-weight: bold;"">e-PBID :</p> 
	   							</td>		
							</tr>
							<tr>
								<td align=""center"">&nbsp;
								</td>
							</tr>
							<tr>
								<td align=""center"">
								</td>
							</tr>
							<tr>
								<td>
	    							<p style=""font-weight: bold;text-align:center;"">POSTAL BALLOT PAPER</p>
								</td>
							</tr>
						</table>
			
					<hr style=""height:5px; background-color: black;""/>
					<table id=""borderimg1"" style="" width:100%; margin-top:25px;"" cellspacing=""0"" cellpadding=""12"">
					
");
            
            #line 478 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

					for(int i = previousLotCount; i < (previousLotCount + nextLotCount); i++)
					   {
						 var j = i+1;

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t <tr>\r\n\t\t\t\t\t\r\n\t\t\t\t\t\t       <td align=\"center\" style=\"border-right:1px black" +
                    " solid; border-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-si" +
                    "ze:20px;\">");
            
            #line 486 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-b" +
                    "ottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px; font-" +
                    "family:");
            
            #line 489 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 489 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 490 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 490 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 491 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 492 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 494 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 499 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 501 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 506 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t\t </tr>\r\n");
            
            #line 512 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

					   }					
					for(var i = 0; i < (10 - nextLotCount); i++)
					   {

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t   <tr style=\"height: 98px;\">\r\n\t\t\t\t\t\t   <td>&nbsp;\r\n\t\t\t\t\t\t   </td>\r\n\t\t\t\t\t\t " +
                    "  </tr>\r\n\r\n");
            
            #line 522 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

					    }
					  

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\r\n\t\t\t\t\t</table>\r\n");
            
            #line 527 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
	
						previousLotCount = previousLotCount + 9;
						nextLotCount = nextLotCount - 9;
		
                   }                                                               
				   
				   if(nextLotCount == threshold)
					   {                                                             

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<p style=\"page-break-after:always;\"></p>\r\n\t\t\t\t\t\t<br />\r\n\t\t\t\t\t\t<table style=" +
                    "\"width:100%\">\r\n\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t   <p style = \"line-height:" +
                    " 20px;font-weight: bold;\">\r\n\t\t\t\t\t\t\t\t\t   <img src = ");
            
            #line 542 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
									   </p>
									</td>
								</tr>
								<tr>
									<td>&nbsp;</td>
								</tr>
								<tr>
									<td>
										<p style=""font-weight: bold;"">e-PBID :</p> 
									</td>		
								</tr>
								<tr>
									<td align=""center"">&nbsp;
									</td>
								</tr>
								<tr>
									<td align=""center"">
									</td>
								</tr>
								<tr>
									<td>
										<p style=""font-weight: bold;text-align:center;"">POSTAL BALLOT PAPER</p>
									</td>
								</tr>
							</table>
				
						<hr style=""height:5px; background-color: black;""/>
						<table id=""borderimg1"" style="" width:100%; margin-top:25px;"" cellspacing=""0"" cellpadding=""12"">
");
            
            #line 571 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

						for(int i = previousLotCount; i < (previousLotCount + nextLotCount); i++)
						   {
							 var j = i+1;

							 var lastIndex=(previousLotCount + nextLotCount)-1;
							 if(i==lastIndex)
								 {

            
            #line default
            #line hidden
            this.Write("\t\t\t \r\n\t\t\t\t\t\t\t\t\t   <tr>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t   <td align=\"center\" style=\"border-r" +
                    "ight:1px black solid; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 583 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:5" +
                    "5%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:18px; font-family:");
            
            #line 586 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 586 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 587 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 587 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 588 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 589 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 591 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%;\" align=\"center\">\r\n\t" +
                    "\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 596 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 598 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid;  width:20%; height:96px;\">&nbsp" +
                    ";</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 603 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\" width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t   </tr>\r\n");
            
            #line 609 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
	   
								   }
								 else
								   {				 

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t <tr>\r\n\t\t\t\t\t\t\t\t\t \r\n\t\t\t\t\t\t\t\t\t   <td align=\"center\" style=\"border-right:1p" +
                    "x black solid; border-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t    <span sty" +
                    "le=\"font-size:20px;\">");
            
            #line 617 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t      </td>\r\n\t\t\t\t\t\t\t\t    <td style=\"border-right:1px black solid" +
                    "; border-bottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:1" +
                    "8px; font-family:");
            
            #line 620 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\"> ");
            
            #line 620 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:11px; line-height:0.5 ; font-famil" +
                    "y:");
            
            #line 621 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FontFamily));
            
            #line default
            #line hidden
            this.Write(";\">");
            
            #line 621 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 622 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 623 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 625 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 630 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 632 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 637 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t\t\t </tr> \r\n\r\n");
            
            #line 644 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

								   }
							 
	
						   }

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\r\n\t\t\t\t\t\t</table>\r\n\r\n");
            
            #line 653 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

						previousLotCount = previousLotCount + 9;
						nextLotCount = nextLotCount - 9;

					   
					   }                                                          

				   
				 }                                                              
            }                                                                    
	}                                                                         
	


            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n\r\n</body>\r\n\r\n\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\12-2-19\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemplateAC.tt"

private global::CandidateDetails.BallotCandidateList _TTfileDictField;

/// <summary>
/// Access the TTfileDict parameter of the template.
/// </summary>
private global::CandidateDetails.BallotCandidateList TTfileDict
{
    get
    {
        return this._TTfileDictField;
    }
}

private string _ImagesrcField;

/// <summary>
/// Access the Imagesrc parameter of the template.
/// </summary>
private string Imagesrc
{
    get
    {
        return this._ImagesrcField;
    }
}

private string _Imagesrc2Field;

/// <summary>
/// Access the Imagesrc2 parameter of the template.
/// </summary>
private string Imagesrc2
{
    get
    {
        return this._Imagesrc2Field;
    }
}

private string _FontFamilyField;

/// <summary>
/// Access the FontFamily parameter of the template.
/// </summary>
private string FontFamily
{
    get
    {
        return this._FontFamilyField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TTfileDictValueAcquired = false;
if (this.Session.ContainsKey("TTfileDict"))
{
    this._TTfileDictField = ((global::CandidateDetails.BallotCandidateList)(this.Session["TTfileDict"]));
    TTfileDictValueAcquired = true;
}
if ((TTfileDictValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TTfileDict");
    if ((data != null))
    {
        this._TTfileDictField = ((global::CandidateDetails.BallotCandidateList)(data));
    }
}
bool ImagesrcValueAcquired = false;
if (this.Session.ContainsKey("Imagesrc"))
{
    this._ImagesrcField = ((string)(this.Session["Imagesrc"]));
    ImagesrcValueAcquired = true;
}
if ((ImagesrcValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imagesrc");
    if ((data != null))
    {
        this._ImagesrcField = ((string)(data));
    }
}
bool Imagesrc2ValueAcquired = false;
if (this.Session.ContainsKey("Imagesrc2"))
{
    this._Imagesrc2Field = ((string)(this.Session["Imagesrc2"]));
    Imagesrc2ValueAcquired = true;
}
if ((Imagesrc2ValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imagesrc2");
    if ((data != null))
    {
        this._Imagesrc2Field = ((string)(data));
    }
}
bool FontFamilyValueAcquired = false;
if (this.Session.ContainsKey("FontFamily"))
{
    this._FontFamilyField = ((string)(this.Session["FontFamily"]));
    FontFamilyValueAcquired = true;
}
if ((FontFamilyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FontFamily");
    if ((data != null))
    {
        this._FontFamilyField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class BallotTemplateACBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
