// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ETPB_BALLOT_Software
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using CandidateDetails;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class BallotTemp : BallotTempBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!DOCTYPE HTML>\r\n<html>\r\n<head>\r\n\t<style>\r\n\t#borderimg1 { \r\n\t\tborder: 9px black" +
                    " solid;\r\n\r\n\t\tborder-image:  url(\'");
            
            #line 19 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc2));
            
            #line default
            #line hidden
            this.Write("\') 34 round;\r\n\t\tborder-image-repeat:repeat;\r\n\t\tborder-image-width:20px;\r\n\t}\r\n\t</s" +
                    "tyle>\r\n</head>\r\n\r\n<body style=\"margin: 20px;\">\r\n\t<table style=\"width:100%\">\r\n\t\t<" +
                    "tr>\r\n\t\t\t<td>\r\n\t\t\t   <p style = \"line-height: 20px;font-weight: bold;\">\r\n\t\t\t   <i" +
                    "mg src = ");
            
            #line 31 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
			   </p>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>
				<p style=""font-weight: bold;"">e-PBID :</p> 
			</td>		
		</tr>
		<tr>
			<td align=""center"">&nbsp;
			</td>
		</tr>
		<tr>
			<td align=""center"">
			</td>
		</tr>
		<tr>
			<td>
				<p style=""font-weight: bold;text-align:center;"">POSTAL BALLOT PAPER</p>
			</td>
		</tr>
	</table>
   
	<hr style=""height:5px; background-color: black;""/>

	");
            
            #line 60 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

	if(TTfileDict.Candidate.Count <= 9)
	{
	
            
            #line default
            #line hidden
            this.Write("\r\n\t\t<table id=\"borderimg1\" style=\" width:100%;\" cellspacing=\"0\" cellpadding=\"7\">\r" +
                    "\n\t\t\t");
            
            #line 66 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

			for(int i = 0; i < TTfileDict.Candidate.Count; i++)
			{
			var j = i+1;
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr>\r\n\t\t\t\t\t<td align=\"center\" style=\"border-right:1px black solid; border-bot" +
                    "tom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 73 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:" +
                    "5px solid black; width:55%;\">\r\n\t\t\t\t\t\t<span style=\"font-size:22px;\"> ");
            
            #line 76 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t");
            
            #line 77 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						if(i != (TTfileDict.Candidate.Count - 1))
						{
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 81 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t");
            
            #line 82 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						}
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 85 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t");
            
            #line 86 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						if(i != (TTfileDict.Candidate.Count - 1))
						{
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 90 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t");
            
            #line 91 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						}
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t</td>\r\n\t\t\t\t\t");
            
            #line 95 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
					{
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; widt" +
                    "h:20%;\" align=\"center\">\r\n\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 100 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t");
            
            #line 102 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					}
					else
					{
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; widt" +
                    "h:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t");
            
            #line 108 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					}
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t</tr" +
                    ">\r\n\t\t\t");
            
            #line 114 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

			}
			
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 117 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

				if(TTfileDict.Candidate.Count < 9)
				{
					for(var i = 0; i < (10 - TTfileDict.Candidate.Count); i++)
					{
					
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t<tr style=\"height: 98px;\">\r\n\t\t\t\t\t\t\t<td>&nbsp;\r\n\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t</tr>\r" +
                    "\n\r\n\t\t\t\t\t");
            
            #line 129 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					}
				}
			
            
            #line default
            #line hidden
            this.Write("\t\t</table>\r\n\r\n\t");
            
            #line 135 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

	}
	else
	{
	
            
            #line default
            #line hidden
            this.Write("\r\n\t\t<table id=\"borderimg1\" style=\" width:100% ;\" cellspacing=\"0\" cellpadding=\"12\"" +
                    ">\r\n\t\t\t");
            
            #line 142 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

			for(int i = 0; i < 9; i++)
			{
			var j = i+1;
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr>\r\n\t\t\t\t\t<td align=\"center\" style=\"border-right:1px black solid; border-bot" +
                    "tom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 149 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:" +
                    "5px solid black; width:55%;\">\r\n\t\t\t\t\t\t<span style=\"font-size:22px;\"> ");
            
            #line 152 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t");
            
            #line 153 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						if(i != (TTfileDict.Candidate.Count - 1))
						{
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 157 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t");
            
            #line 158 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						}
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 161 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t");
            
            #line 162 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						if(i != (TTfileDict.Candidate.Count - 1))
						{
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 166 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t");
            
            #line 167 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						}
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t</td>\r\n\t\t\t\t\t");
            
            #line 171 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
					{
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; widt" +
                    "h:20%;\" align=\"center\">\r\n\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 176 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t");
            
            #line 178 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					}
					else
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; widt" +
                    "h:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t");
            
            #line 183 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					}
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>" +
                    "\r\n\t\t\t");
            
            #line 189 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

			}
			
            
            #line default
            #line hidden
            this.Write("\t\t</table>\r\n\r\n\t\t");
            
            #line 194 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

			int threshold = 9;
			int nextLotCount = TTfileDict.Candidate.Count - threshold;
			int previousLotCount = threshold;

			while(nextLotCount > 0)
			{
				if(nextLotCount > threshold)
				{
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<p style=\"page-break-after:always;\"></p>\r\n\r\n\t\t\t\t\t<br />\r\n\r\n\t\t\t\t\t<table style" +
                    "=\"width:100%\">\r\n\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t<p style = \"line-height: 20px;f" +
                    "ont-weight: bold;\">\r\n\t\t\t\t\t\t\t\t<img src = ");
            
            #line 212 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
								</p>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td>
								<p style=""font-weight: bold;"">e-PBID :</p> 
							</td>		
						</tr>
						<tr>
							<td align=""center"">&nbsp;
							</td>
						</tr>
						<tr>
							<td align=""center"">
							</td>
						</tr>
						<tr>
							<td>
								<p style=""font-weight: bold;text-align:center;"">POSTAL BALLOT PAPER</p>
							</td>
						</tr>
					</table>

					<hr style=""height:5px; background-color: black;""/>
					
					<table id=""borderimg1"" style="" width:100% ;"" cellspacing=""0"" cellpadding=""12"">
						");
            
            #line 242 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						for(int i = previousLotCount; i < (previousLotCount + threshold); i++)
						{
						var j = i+1;
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td align=\"center\" style=\"border-right:1px black solid; bord" +
                    "er-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 249 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-b" +
                    "ottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px;\"> ");
            
            #line 252 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 253 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									if(i != (TTfileDict.Candidate.Count - 1))
									{
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 257 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 258 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									}
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 261 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 262 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									if(i != (TTfileDict.Candidate.Count - 1))
									{
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 266 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 267 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									}
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 271 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 276 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 278 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black;" +
                    " width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 283 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 289 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						}
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t</table>\r\n\t\t\t\t\t");
            
            #line 293 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"


					previousLotCount = previousLotCount + 9;
					nextLotCount = nextLotCount - 9;
				}
				else
				{
					while (nextLotCount > 0 && nextLotCount <= threshold)
					{
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<p style=\"page-break-after:always;\"></p>\r\n\t\t\t\t\t\t<br />\r\n\r\n\t\t\t\t\t\t<table styl" +
                    "e=\"width:100%\">\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t   <p style = \"line-height: " +
                    "20px;font-weight: bold;\">\r\n\t\t\t\t\t\t\t\t   <img src = ");
            
            #line 310 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Imagesrc));
            
            #line default
            #line hidden
            this.Write(@" alt=""eci_logo"" style='vertical-align: middle' height=""42"" width=""42"" /> Election Commission of India
								   </p>
								</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
							</tr>
							<tr>
								<td>
									<p style=""font-weight: bold;"">e-PBID :</p> 
								</td>		
							</tr>
							<tr>
								<td align=""center"">&nbsp;
								</td>
							</tr>
							<tr>
								<td align=""center"">
								</td>
							</tr>
							<tr>
								<td>
									<p style=""font-weight: bold;text-align:center;"">POSTAL BALLOT PAPER</p>
								</td>
							</tr>
						</table>
			
							<hr style=""height:5px; background-color: black;""/>
						<table id=""borderimg1"" style="" width:100%;"" cellspacing=""0"" cellpadding=""12"">
						");
            
            #line 339 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						for(int i = previousLotCount; i < (previousLotCount + nextLotCount); i++)
						{
						var j = i+1;
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td align=\"center\" style=\"border-right:1px black solid; bord" +
                    "er-bottom:5px solid black; width:5%\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:20px;\">");
            
            #line 346 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-b" +
                    "ottom:5px solid black; width:55%;\">\r\n\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px;\"> ");
            
            #line 349 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameOL));
            
            #line default
            #line hidden
            this.Write(" </span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 350 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									if(i != (TTfileDict.Candidate.Count - 1))
									{
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 354 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameOL));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 355 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									}
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<span style=\"font-size:22px; margin-top:5px;\">");
            
            #line 358 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].CandidateNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 359 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									if(i != (TTfileDict.Candidate.Count - 1))
									{
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<span style=\"font-size:15px;\">");
            
            #line 363 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TTfileDict.Candidate[i].PartyNameENG));
            
            #line default
            #line hidden
            this.Write("</span><br/>\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 364 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

									}
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 368 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								if(this.TTfileDict.Candidate[i].CandidatePhoto.Length > 1)
								{
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%;\" align=\"center\">\r\n\t\t\t\t\t\t\t\t\t\t<img id=\"blah\" src=\"");
            
            #line 373 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("data:image/jpg;base64," + Convert.ToBase64String(this.TTfileDict.Candidate[i].CandidatePhoto)));
            
            #line default
            #line hidden
            this.Write("\" alt=\"your image\" style=\"height: 96px; width: 74px;\" />\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t" +
                    "\t");
            
            #line 375 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								}
								else
								{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<td style=\"border-right:1px black solid; border-bottom:5px solid black; " +
                    "width:20%; height:96px;\">&nbsp;</td>\r\n\t\t\t\t\t\t\t\t");
            
            #line 380 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								}
								
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<td style=\"border-bottom:5px solid black; width:20%\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t" +
                    "\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 386 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

						}
						
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t");
            
            #line 390 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

							if(nextLotCount < 9)
							{
								for(var i = 0; i < (10 - nextLotCount); i++)
								{
								
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t<tr style=\"height: 98px;\">\r\n\t\t\t\t\t\t\t\t\t<td>&nbsp;\r\n\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t" +
                    "\t\t</tr>\r\n\r\n\t\t\t\t\t\t\t\t");
            
            #line 402 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

								}
							}
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t</table>\r\n\t\t\t\t\t");
            
            #line 407 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

					previousLotCount = previousLotCount + 9;
					nextLotCount = nextLotCount - 9;
				}
			}
		}
	}
	
            
            #line default
            #line hidden
            this.Write("</body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "F:\Sayali Rane\sayali\25-10-2017 from vijay\ETPB software in wpf\test trial rdlc\ETPB BALLOT Software\ETPB BALLOT Software\BallotTemp.tt"

private global::CandidateDetails.BallotCandidateList _TTfileDictField;

/// <summary>
/// Access the TTfileDict parameter of the template.
/// </summary>
private global::CandidateDetails.BallotCandidateList TTfileDict
{
    get
    {
        return this._TTfileDictField;
    }
}

private string _ImagesrcField;

/// <summary>
/// Access the Imagesrc parameter of the template.
/// </summary>
private string Imagesrc
{
    get
    {
        return this._ImagesrcField;
    }
}

private string _Imagesrc2Field;

/// <summary>
/// Access the Imagesrc2 parameter of the template.
/// </summary>
private string Imagesrc2
{
    get
    {
        return this._Imagesrc2Field;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TTfileDictValueAcquired = false;
if (this.Session.ContainsKey("TTfileDict"))
{
    this._TTfileDictField = ((global::CandidateDetails.BallotCandidateList)(this.Session["TTfileDict"]));
    TTfileDictValueAcquired = true;
}
if ((TTfileDictValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TTfileDict");
    if ((data != null))
    {
        this._TTfileDictField = ((global::CandidateDetails.BallotCandidateList)(data));
    }
}
bool ImagesrcValueAcquired = false;
if (this.Session.ContainsKey("Imagesrc"))
{
    this._ImagesrcField = ((string)(this.Session["Imagesrc"]));
    ImagesrcValueAcquired = true;
}
if ((ImagesrcValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imagesrc");
    if ((data != null))
    {
        this._ImagesrcField = ((string)(data));
    }
}
bool Imagesrc2ValueAcquired = false;
if (this.Session.ContainsKey("Imagesrc2"))
{
    this._Imagesrc2Field = ((string)(this.Session["Imagesrc2"]));
    Imagesrc2ValueAcquired = true;
}
if ((Imagesrc2ValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Imagesrc2");
    if ((data != null))
    {
        this._Imagesrc2Field = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class BallotTempBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
